---
title: "Untitled"
output: html_document
date: '`r Sys.Date()`'
---

```{r}
library(tidygraph)
library(tidyverse)
library(ggraph)
theme_set(theme_bw())
```

```{r}
nodes <- read_csv("https://github.com/krisrs1128/stat992_f23/raw/main/activities/week9/climate-nodes.csv")
edges <- read_csv("https://github.com/krisrs1128/stat992_f23/raw/main/activities/week9/climate-edges.csv")

nodes
edges
```

```{r}
library(forcats)

climate_graph <- tbl_graph(nodes, edges) |>
  mutate(
    session_grouped = fct_lump_n(session, 6),
    genre_grouped = fct_lump_n(genre, 6)
  )

climate_graph |>
  distinct(session_grouped) |>
  pull(session_grouped)

climate_graph |>
  as_tibble() |>
  count(genre) |>
  arrange(-n)
```

```{r, fig.width = 7, fig.height = 3}
ggraph(climate_graph) +
  geom_edge_link(edge_color = "#d3d3d3") +
  geom_node_point(aes(col = session_grouped, size = views)) +
  scale_size(range = c(1, 10)) +
  facet_wrap(~ genre)
```

```{r}
ggraph(climate_graph, "matrix") +
  geom_edge_tile() +
  geom_node_point(aes(col = session_grouped), size = 5, x = -1) +
  geom_node_point(aes(col = session_grouped), size = 5, y = -1)
```