---
title: "Improving an App"
output: html_document
---

```{r}
library(tidyverse)
```

1. [Improving an app] Make the following apps more concise, modular, and
readable by using reactive expressions to capture duplicated computation and /
or externalizing complex computations into functions which are defined outside
of the server.

a. Program (a)

```{r, eval = FALSE}
library(shiny)

ui <- fluidPage(
  titlePanel("Calculator"),
  numericInput("x", "Enter the value of x", 0),
  textOutput("f1"),
  textOutput("f2"),
  textOutput("f3")
)

server <- function(input, output) {
  output$f1 <- renderText({ 3 * input$x ^ 2 + 3})
  output$f2 <- renderText({ sqrt(3 * input$x ^ 2 + 3) - 5})
  output$f3 <- renderText({ 30 * input$x ^ 2 + 30})
}
    
shinyApp(ui, server)
```


```{r}
ui <- fluidPage(
  titlePanel("Calculator"),
  numericInput("x", "Enter the value of x", 0),
  textOutput("f1"),
  textOutput("f2"),
  textOutput("f3")
)

server <- function(input, output) {
  # have them write out the reactive graph
  f <- reactive({
    3 * input$x ^ 2 + 3
  })
  
  output$f1 <- renderText(f())
  output$f2 <- renderText({ sqrt(f()) - 5})
  output$f3 <- renderText({ 10 * f() })
}
    
shinyApp(ui, server)
```


b. Program (b)
    
```{r, eval = FALSE}
penguins <- read_csv("https://uwmadison.box.com/shared/static/ijh7iipc9ect1jf0z8qa2n3j7dgem1gh.csv")
islands <- unique(penguins$island)
species <- unique(penguins$species)

ui <- fluidPage(
  titlePanel("Penguins Plot"),
  selectInput("species", "Species", species, multiple = TRUE),
  selectInput("island", "Island", islands, multiple = TRUE),
  selectInput("var1", "First Variable", colnames(penguins)[3:6]),
  selectInput("var2", "Second Variable", colnames(penguins)[3:6]),
  plotOutput("scatterplot"),
  plotOutput("histogram1"),
  plotOutput("histogram2"),
)

# also work through the reactive graph on this problem

server <- function(input, output) {
  current_data <- reactive({
    penguins %>%
      filter(
        island %in% input$island,
        species %in% input$species
      )
  })
  
  output$scatterplot <- renderPlot({
    ggplot(current_data()) +
      geom_point(aes(.data[[input$var1]], .data[[input$var2]]))
  })
  
  output$histogram1 <- renderPlot({
    ggplot(current_data()) +
      geom_histogram(aes(.data[[input$var1]]))
  })
  
  output$histogram2 <- renderPlot({
    ggplot(current_data()) +
      geom_histogram(aes(.data[[input$var2]]))
  })
  
}

shinyApp(ui, server)
```

```{r}
ui <- fluidPage(
  titlePanel("Penguins Plot"),
  selectInput("species", "Species", species, multiple = TRUE),
  selectInput("island", "Island", islands, multiple = TRUE),
  selectInput("var1", "First Variable", colnames(penguins)[3:6]),
  selectInput("var2", "Second Variable", colnames(penguins)[3:6]),
  plotOutput("scatterplot"),
  plotOutput("histogram1"),
  plotOutput("histogram2"),
)

# also work through the reactive graph on this problem

histogram_fun <- function(df, var) {
    ggplot(df) +
      geom_histogram(aes(.data[[var]]))
}

server <- function(input, output) {
  current_data <- reactive({
    penguins %>%
      filter(
        island %in% input$island,
        species %in% input$species
      )
  })
  
  output$scatterplot <- renderPlot({
    ggplot(current_data()) +
      geom_point(aes(.data[[input$var1]], .data[[input$var2]]))
  })
  
  output$histogram1 <- renderPlot(
    histogram_fun(current_data(), input$var1)
  )
  
  output$histogram2 <- renderPlot(
    histogram_fun(current_data(), input$var2)
  )
}

shinyApp(ui, server)
```


```{r}
library(shiny)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(bootswatch = "cerulean"),
  titlePanel("Penguins Plot"),
  selectInput("species", "Species", species, multiple = TRUE),
  selectInput("island", "Island", islands, multiple = TRUE),
  selectInput("var1", "First Variable", colnames(penguins)[3:6]),
  selectInput("var2", "Second Variable", colnames(penguins)[3:6]),
  fluidRow(
    column(8, plotOutput("scatterplot")),
    column(4,
      plotOutput("histogram1", height = 200),
      plotOutput("histogram2", height = 200)
    )
  )
)

# also work through the reactive graph on this problem

histogram_fun <- function(df, var) {
    ggplot(df) +
      geom_histogram(aes(.data[[var]]))
}

server <- function(input, output) {
  current_data <- reactive({
    penguins %>%
      filter(
        island %in% input$island,
        species %in% input$species
      )
  })
  
  output$scatterplot <- renderPlot({
    ggplot(current_data()) +
      geom_point(aes(.data[[input$var1]], .data[[input$var2]]))
  })
  
  output$histogram1 <- renderPlot(
    histogram_fun(current_data(), input$var1)
  )
  
  output$histogram2 <- renderPlot(
    histogram_fun(current_data(), input$var2)
  )
}

shinyApp(ui, server)
```